name: E2E Tests with Cypress

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: yarn --frozen-lockfile --silent
      - run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn sandbox:dev
          working-directory: e2e
          parallel: true
          wait-on: 'http://localhost:1234'
          wait-on-timeout: 120
          browser: chrome
