name: E2E Tests with Cypress

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile --silent

      - name: Build Packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Run Sandbox
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: sandbox:dev

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: e2e
          wait-on: 'http://localhost:1234'
          browser: chrome
