name: E2E Tests with Cypress

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: yarn --frozen-lockfile --silent
      - run: yarn build
      - run: yarn sandbox:build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npx serve -s ../sandbox/dist -p 3000 --yes
          working-directory: e2e
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
